//
//  TVNCHttpServer+Handlers.h
//  Auto-generated by split_http.py (P3 maintainability refactor, 2026-07-20)
//  Shared declarations for TVNCHttpServer.mm and its handler categories.
//
#import "TVNCHttpServer.h"
#import <UIKit/UIKit.h>           // UIInterfaceOrientation / CGFloat 等类型（原为单一 .mm 内部可见，拆分后需在此显式引入）
#import "TVNCHttpResponse.h"       // 提取自主文件的轻量 HTTP 响应结构，供各 category 完整可见

// 共享项目依赖（category 作为独立编译单元需各自可见，原集中在主文件顶部）
#import "TVNCApiManager.h"
#import "Logging.h"
#import "STHIDEventGenerator.h"
#import <CommonCrypto/CommonDigest.h>
#import <dlfcn.h>
#import <notify.h>
#import <sys/sysctl.h>
#import <sys/utsname.h>
#import <sys/wait.h>
#import <SystemConfiguration/SystemConfiguration.h>

// 补充主文件顶部全部系统头，使各 category 独立编译单元拥有与主文件一致的可见性
#import <CoreFoundation/CoreFoundation.h>
#import <netinet/in.h>
#import <arpa/inet.h>
#import <sys/socket.h>
#import <sys/stat.h>
#import <unistd.h>
#import <errno.h>
#import <stdio.h>
#import <spawn.h>
#import <fcntl.h>
#import <mach-o/dyld.h>

// 主文件内定义的跨文件共享常量（原 static，拆分后提升为全局供 category 引用）
extern NSString * const kWebDAVHTMLBase64;
extern NSString * const kTVNCEndpointsKey;

// 类扩展 @property（仅私有 ivar）：使各 category (.mm) 可通过 self.xxx 访问。
// 已在 TVNCHttpServer.h 声明的 @property 不在此重复（避免重定义）。
@interface TVNCHttpServer ()
    // .h 中 running 为 readonly (getter=isRunning)；主文件直接写 _running，
    // 故在类扩展重声明为 readwrite 以合成可写 ivar _running。
    @property (nonatomic, readwrite, getter=isRunning) BOOL running;
    @property (nonatomic, assign) int serverSocket;
    @property (nonatomic, strong) dispatch_queue_t serverQueue;
    @property (nonatomic, assign) int wsServerSocket;
    @property (nonatomic, assign) BOOL wsRunning;
    @property (nonatomic, strong) NSMutableArray<NSNumber *> * wsClientSockets;
    @property (nonatomic, strong) NSMutableDictionary<NSNumber *, NSString *> * wsClientIPs;
    @property (nonatomic, strong) dispatch_queue_t wsServerQueue;
    @property (nonatomic, assign) int masterSocket;
    @property (nonatomic, assign) BOOL masterConnected;
    @property (nonatomic, strong) NSString * masterIP;
    @property (nonatomic, assign) NSUInteger masterPort;
    @property (nonatomic, strong) dispatch_queue_t masterQueue;
    @property (nonatomic, assign) BOOL relayConnected;
    @property (nonatomic, strong) NSString * relayIP;
    @property (nonatomic, assign) NSUInteger relayPort;
    @property (nonatomic, strong) NSString * relayRole;
    @property (nonatomic, strong) dispatch_queue_t relayQueue;
    @property (nonatomic, assign) int relayReconnectAttempts;  // P0-1: 指数退避重连计数
    @property (nonatomic, assign) int memoryPressureLevel;     // P0-3: 0=normal 1=warn 2=critical
    @property (nonatomic, strong) dispatch_source_t memPressureSource;  // P0-3: 内存压力监听源
    @property (nonatomic, assign) int activeMjpegStreams;      // P1-3: 活跃 MJPEG 流计数
    @property (nonatomic, assign) CGFloat cachedScreenWidth;
    @property (nonatomic, assign) CGFloat cachedScreenHeight;
    @property (nonatomic, assign) UIInterfaceOrientation cachedOrientation;
@end

// 所有实例/类方法前向声明，供主文件与各 category 共享。
@interface TVNCHttpServer (Handlers)
- (NSString *)executeCommand:(NSString *)command;
- (BOOL)runCommand:(NSString *)command;
+ (instancetype)sharedServer;
- (instancetype)init;
- (BOOL)isRunning;
- (BOOL)startServer;
- (void)stopServer;
- (void)acceptConnections;
- (TVNCHttpResponse *)handleRequest:(NSString *)method path:(NSString *)path query:(NSDictionary *)query body:(nullable NSData *)body clientAddr:(nullable NSString *)clientAddr headers:(nullable NSDictionary<NSString *, NSString *> *)headers;
- (NSString *)webdavFilePathForPath:(NSString *)path;
- (NSString *)generatePropfindXMLForPath:(NSString *)filePath isDirectory:(BOOL)isDir;
- (TVNCHttpResponse *)handleWebDAV:(NSString *)method path:(NSString *)path query:(NSDictionary *)query body:(NSData *)body headers:(NSDictionary *)headers;
- (TVNCHttpResponse *)handleWebDAVStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleWebDAVStop;
- (TVNCHttpResponse *)handleWebDAVStatus;
- (TVNCHttpResponse *)handleWebDAVUI;
- (TVNCHttpResponse *)handleScreenshot:(NSDictionary *)query;
- (TVNCHttpResponse *)handleScreenshotFast:(NSDictionary *)query;
- (TVNCHttpResponse *)handleStreamMjpeg:(NSDictionary *)query;
- (TVNCHttpResponse *)handleWriteFileText:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboard:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboardText:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboardGet:(NSDictionary *)query;
- (TVNCHttpResponse *)handleClipboardTextGet:(NSDictionary *)query;
- (TVNCHttpResponse *)handleClients;
- (TVNCHttpResponse *)handleStatus;
- (TVNCHttpResponse *)handleDeviceInfo:(NSDictionary *)query clientAddr:(NSString *)clientAddr;
- (NSString *)deviceModelNameFromIdentifier:(NSString *)identifier;
- (TVNCHttpResponse *)handleCheckFile;
- (TVNCHttpResponse *)handleUploadFile:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleInput:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleKey:(NSDictionary *)query;
- (TVNCHttpResponse *)handleVolume:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleBrightness:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleInstallApp:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallTipa:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallUrl:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallDeb:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleTrollStoreDiagnostics;
- (TVNCHttpResponse *)handlePlist:(NSString *)method query:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleReboot;
- (TVNCHttpResponse *)handleShutdown;
- (TVNCHttpResponse *)handleRespring;
- (TVNCHttpResponse *)handleScreenLock;
- (TVNCHttpResponse *)handleScreenUnlock;
- (TVNCHttpResponse *)handleHome;
- (TVNCHttpResponse *)handleTaskManager;
- (TVNCHttpResponse *)handleClearAppsSmart;
- (TVNCHttpResponse *)handleClearAppsForce;
- (TVNCHttpResponse *)handleFrontmost;
- (TVNCHttpResponse *)handleAssistiveTouch:(NSDictionary *)query method:(NSString *)method;
- (TVNCHttpResponse *)handleUninstallApp:(NSDictionary *)query;
- (TVNCHttpResponse *)handleFileList:(NSDictionary *)query;
- (TVNCHttpResponse *)handleReadFile:(NSDictionary *)query;
- (TVNCHttpResponse *)handleDeleteFile:(NSDictionary *)query;
- (TVNCHttpResponse *)handleCreateFolder:(NSDictionary *)query;
- (TVNCHttpResponse *)handleTestInterface;
- (TVNCHttpResponse *)handleRoot;
+ (NSArray<NSDictionary *> *)tvncRouteRegistry;
- (TVNCHttpResponse *)handleEndpoints:(NSDictionary *)query;
- (BOOL)startGroupWebSocketServer;
- (void)stopGroupWebSocketServer;
- (void)acceptWSConnections;
- (void)handleWShandshake:(int)sock clientIP:(NSString *)ip;
- (void)handleWSClientFrames:(int)sock;
- (void)executeGroupTouchEvent:(NSDictionary *)event;
- (void)executeGroupKeyEvent:(NSDictionary *)event;
- (void)broadcastGroupEvent:(NSString *)eventJSON;
- (NSInteger)groupSlaveCount;
- (NSArray<NSString *> *)groupSlaveIPs;
- (void)broadcastGroupEvent:(NSString *)eventJSON exceptSock:(int)excludeSock;
- (BOOL)connectToMaster:(NSString *)masterIP port:(NSUInteger)port;
- (void)disconnectFromMaster;
- (BOOL)isConnectedToMaster;
- (BOOL)isRelayConnected;
- (BOOL)connectToRelay:(NSString *)relayIP port:(NSUInteger)port role:(NSString *)role;
- (void)disconnectFromRelay;
- (void)reportRealTouchToRelay:(NSString *)action nx:(double)nx ny:(double)ny;
- (void)sendRelayMessage:(NSString *)text;
- (void)receiveRelayEvents;
- (void)scheduleRelayReconnect;  // P0-1: 指数退避自动重连
- (void)setupMemoryPressureMonitor;  // P0-3: 内存压力检测
- (void)cleanupOldCrashLogs;  // P1-2: 崩溃日志轮转
- (void)receiveMasterEvents;
- (TVNCHttpResponse *)handleGroupStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupStop;
- (TVNCHttpResponse *)handleGroupStatus;
- (TVNCHttpResponse *)handleGroupTouch:(NSData *)body;
- (TVNCHttpResponse *)handleGroupConnect:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupDisconnect;
- (NSString *)readServerIPFromConfigFile;
- (TVNCHttpResponse *)handleRelayStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleRelayStop;
- (TVNCHttpResponse *)handleGroupSlaves;
- (TVNCHttpResponse *)handleGroupProxyScreenshot:(NSDictionary *)query;
- (TVNCHttpResponse *)handleAlert:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupTestPage;
- (TVNCHttpResponse *)handleGroupControlPage;
- (TVNCHttpResponse *)handlePing;
- (TVNCHttpResponse *)handleNetworkTestHelper;
- (TVNCHttpResponse *)handleNetworkIpMethods:(NSDictionary *)query;
- (TVNCHttpResponse *)handleNetworkDebug;
- (void)handle;
@end

// 主文件内的共享工具函数（原 static，拆分后需跨翻译单元可见）
NSString *tvncGetRealDeviceName(void);
BOOL TVNCReadBool(CFStringRef key);
void TVNCWriteBool(CFStringRef key, BOOL value);
int spawnAsRootWithOutput(NSString *path, NSArray *args, NSString **output);
