//
//  TVNCHttpServer+Handlers.h
//  Auto-generated by split_http.py (P3 maintainability refactor, 2026-07-20)
//  Shared declarations for TVNCHttpServer.mm and its handler categories.
//
#import "TVNCHttpServer.h"

// 类扩展 @property（仅私有 ivar）：使各 category (.mm) 可通过 self.xxx 访问。
// 已在 TVNCHttpServer.h 声明的 @property 不在此重复（避免重定义）。
@interface TVNCHttpServer ()
    @property (nonatomic, assign) int _serverSocket;
    @property (nonatomic, assign) dispatch_queue_t _serverQueue;
    @property (nonatomic, assign) int _wsServerSocket;
    @property (nonatomic, assign) BOOL _wsRunning;
    @property (nonatomic, strong) NSMutableArray<NSNumber *> * _wsClientSockets;
    @property (nonatomic, strong) NSMutableDictionary<NSNumber *, NSString *> * _wsClientIPs;
    @property (nonatomic, assign) dispatch_queue_t _wsServerQueue;
    @property (nonatomic, assign) int _masterSocket;
    @property (nonatomic, assign) BOOL _masterConnected;
    @property (nonatomic, strong) NSString * _masterIP;
    @property (nonatomic, assign) NSUInteger _masterPort;
    @property (nonatomic, assign) dispatch_queue_t _masterQueue;
    @property (nonatomic, assign) BOOL _relayConnected;
    @property (nonatomic, strong) NSString * _relayIP;
    @property (nonatomic, assign) NSUInteger _relayPort;
    @property (nonatomic, strong) NSString * _relayRole;
    @property (nonatomic, assign) dispatch_queue_t _relayQueue;
    @property (nonatomic, assign) CGFloat _cachedScreenWidth;
    @property (nonatomic, assign) CGFloat _cachedScreenHeight;
    @property (nonatomic, assign) UIInterfaceOrientation _cachedOrientation;
@end

// 所有实例/类方法前向声明，供主文件与各 category 共享。
@interface TVNCHttpServer (Handlers)
- (NSString *)executeCommand:(NSString *)command;
- (BOOL)runCommand:(NSString *)command;
+ (instancetype)sharedServer;
- (instancetype)init;
- (BOOL)isRunning;
- (BOOL)startServer;
- (void)stopServer;
- (void)acceptConnections;
- (TVNCHttpResponse *)handleRequest:(NSString *)method path:(NSString *)path query:(NSDictionary *)query body:(nullable NSData *)body clientAddr:(nullable NSString *)clientAddr headers:(nullable NSDictionary<NSString *, NSString *> *)headers;
- (NSString *)webdavFilePathForPath:(NSString *)path;
- (NSString *)generatePropfindXMLForPath:(NSString *)filePath isDirectory:(BOOL)isDir;
- (TVNCHttpResponse *)handleWebDAV:(NSString *)method path:(NSString *)path query:(NSDictionary *)query body:(NSData *)body headers:(NSDictionary *)headers;
- (TVNCHttpResponse *)handleWebDAVStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleWebDAVStop;
- (TVNCHttpResponse *)handleWebDAVStatus;
- (TVNCHttpResponse *)handleWebDAVUI;
- (TVNCHttpResponse *)handleScreenshot:(NSDictionary *)query;
- (TVNCHttpResponse *)handleScreenshotFast:(NSDictionary *)query;
- (TVNCHttpResponse *)handleStreamMjpeg:(NSDictionary *)query;
- (TVNCHttpResponse *)handleWriteFileText:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboard:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboardText:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleClipboardGet:(NSDictionary *)query;
- (TVNCHttpResponse *)handleClipboardTextGet:(NSDictionary *)query;
- (TVNCHttpResponse *)handleClients;
- (TVNCHttpResponse *)handleStatus;
- (TVNCHttpResponse *)handleDeviceInfo:(NSDictionary *)query clientAddr:(NSString *)clientAddr;
- (NSString *)deviceModelNameFromIdentifier:(NSString *)identifier;
- (TVNCHttpResponse *)handleCheckFile;
- (TVNCHttpResponse *)handleUploadFile:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleInput:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleKey:(NSDictionary *)query;
- (TVNCHttpResponse *)handleVolume:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleBrightness:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleInstallApp:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallTipa:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallUrl:(NSDictionary *)query;
- (TVNCHttpResponse *)handleInstallDeb:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleTrollStoreDiagnostics;
- (TVNCHttpResponse *)handlePlist:(NSString *)method query:(NSDictionary *)query body:(NSData *)body;
- (TVNCHttpResponse *)handleReboot;
- (TVNCHttpResponse *)handleShutdown;
- (TVNCHttpResponse *)handleRespring;
- (TVNCHttpResponse *)handleScreenLock;
- (TVNCHttpResponse *)handleScreenUnlock;
- (TVNCHttpResponse *)handleHome;
- (TVNCHttpResponse *)handleTaskManager;
- (TVNCHttpResponse *)handleClearAppsSmart;
- (TVNCHttpResponse *)handleClearAppsForce;
- (TVNCHttpResponse *)handleFrontmost;
- (TVNCHttpResponse *)handleAssistiveTouch:(NSDictionary *)query method:(NSString *)method;
- (TVNCHttpResponse *)handleUninstallApp:(NSDictionary *)query;
- (TVNCHttpResponse *)handleFileList:(NSDictionary *)query;
- (TVNCHttpResponse *)handleReadFile:(NSDictionary *)query;
- (TVNCHttpResponse *)handleDeleteFile:(NSDictionary *)query;
- (TVNCHttpResponse *)handleCreateFolder:(NSDictionary *)query;
- (TVNCHttpResponse *)handleTestInterface;
- (TVNCHttpResponse *)handleRoot;
+ (NSArray<NSDictionary *> *)tvncRouteRegistry;
- (TVNCHttpResponse *)handleEndpoints:(NSDictionary *)query;
- (BOOL)startGroupWebSocketServer;
- (void)stopGroupWebSocketServer;
- (void)acceptWSConnections;
- (void)handleWShandshake:(int)sock clientIP:(NSString *)ip;
- (void)handleWSClientFrames:(int)sock;
- (void)executeGroupTouchEvent:(NSDictionary *)event;
- (void)executeGroupKeyEvent:(NSDictionary *)event;
- (void)broadcastGroupEvent:(NSString *)eventJSON;
- (NSInteger)groupSlaveCount;
- (NSArray<NSString *> *)groupSlaveIPs;
- (void)broadcastGroupEvent:(NSString *)eventJSON exceptSock:(int)excludeSock;
- (BOOL)connectToMaster:(NSString *)masterIP port:(NSUInteger)port;
- (void)disconnectFromMaster;
- (BOOL)isConnectedToMaster;
- (BOOL)isRelayConnected;
- (BOOL)connectToRelay:(NSString *)relayIP port:(NSUInteger)port role:(NSString *)role;
- (void)disconnectFromRelay;
- (void)reportRealTouchToRelay:(NSString *)action nx:(double)nx ny:(double)ny;
- (void)sendRelayMessage:(NSString *)text;
- (void)receiveRelayEvents;
- (void)receiveMasterEvents;
- (TVNCHttpResponse *)handleGroupStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupStop;
- (TVNCHttpResponse *)handleGroupStatus;
- (TVNCHttpResponse *)handleGroupTouch:(NSData *)body;
- (TVNCHttpResponse *)handleGroupConnect:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupDisconnect;
- (NSString *)readServerIPFromConfigFile;
- (TVNCHttpResponse *)handleRelayStart:(NSDictionary *)query;
- (TVNCHttpResponse *)handleRelayStop;
- (TVNCHttpResponse *)handleGroupSlaves;
- (TVNCHttpResponse *)handleGroupProxyScreenshot:(NSDictionary *)query;
- (TVNCHttpResponse *)handleAlert:(NSDictionary *)query;
- (TVNCHttpResponse *)handleGroupTestPage;
- (TVNCHttpResponse *)handleGroupControlPage;
- (TVNCHttpResponse *)handlePing;
- (TVNCHttpResponse *)handleNetworkTestHelper;
- (TVNCHttpResponse *)handleNetworkIpMethods:(NSDictionary *)query;
- (TVNCHttpResponse *)handleNetworkDebug;
- (void)handle;
@end
